Feature/#1 channel 모듈 구현
ft-transcendence-seoul/backend pull request #23
Opened 2023-11-09 19:27 UTC by PotentialY1

✔Pull request의 세부 사항은 issues 참고 바랍니다.
- Files changed [package-lock.json]에서 bcypt 패키지 설치로 인한 라인 수 증가
- 우진님 고안 중인 채널 controller에 있는 ownerGuard, adminGuard 기능 추가 시 service에 있는 관리자 권한 확인 코드 생략 가능

✔Comment 필요한 사항
- mute 기능은 우진님이 따로 구현하려고 하신 걸로 인지하고 있어서 일단 제외하였는데 이 부분 확인 바랍니다. 

@Column({ default: false })
  is_muted: boolean;

  @Column({ default: 5 })
  mutedTime: number;

  @CreateDateColumn()
  createdAt: Date;
- mute 기능은 위의 entity로 구현 예정입니다.

2023-11-10 09:00 UTC, izone00 reviewed
requestingUser에 대한 예외처리가 거의 다 이상하거든요
예외처리가 안되면 코드는 없이 그냥 주석만 달고
메소드 동작만 구현하는게 좋을 것 같아요

2023-11-10 09:00 UTC, izone00 commented on src/channels/entities/channel.entity.ts
> +
채널에 user는 owner인가요?
위에 ChannelRelation에서 isOwner정의 했으니 빼야될것 같아요

2023-11-10 09:00 UTC, izone00 commented on src/users/user.entity.ts
> +
여기도 user에서 channel을 조회할 일은 없어서 지워야될것 같아요

2023-11-10 09:00 UTC, izone00 commented on src/channels/channels.service.ts
> +
나갈때 더이상 사람이 없다면  channel을 지워줘야할거 같아요

2023-11-10 09:00 UTC, izone00 commented on src/channels/channels.service.ts
> +
requestingUserRelation가 채널의 소유자이면서 isAdmin이 변경되는 대상도 되고 있는데
이게 맞나요?
이것도  requestingUser에 대한 예외처리는 없이 
그냥 변경되는 대상의 idAdmin만 바꾸는 식으로 일단 하는게 좋을 것 같아요.

2023-11-10 09:00 UTC, izone00 commented on src/channels/channels.service.ts
> +
이건 채널 초대에 대한 entity가 erd에 따로 있어서 
그걸 이용하셔야되요.
초대를 수락하고 채널에 들어가게끔 해야 될것같아요

2023-11-10 09:00 UTC, izone00 commented on src/channels/channels.controller.ts
> +@Controller('channels')
여기에 userController처럼 userGuard써주세요

2023-11-10 09:06 UTC, izone00 reviewed
requestingUser에 대한 예외처리가 거의 다 이상하거든요
예외처리가 안되면 코드는 없이 그냥 주석만 달고
메소드 동작만 구현하는게 좋을 것 같아요

2023-11-10 09:06 UTC, izone00 commented on src/channels/channels.service.ts
> +    const earliestOwnerRelation = await this.entityManager
위에서는 this.channelRelationRepository 쓰다가
왜 여긴 entityManager를 쓰신건가요?

2023-11-10 09:06 UTC, izone00 commented on src/channels/channels.service.ts
> +      .map((relation) => relation.user);
.fileter.map보다는
```
ChannelRelationRepo.find({
  where: {  
    id: channelId,
    isBanned: true
   }
})
```

하시면 아마 바로 찾을수 있을거에요

2023-11-10 09:09 UTC, izone00 commented on src/channels/channels.service.ts
> +
아래 ban메소드 두개는 requestingUserRelation을 channel.user로 하는데
함수 내용이 말이 전혀 안되는 상황이라
그냥 requestingUserRelation에 대한 예외처리를 뺴고 우선 만드는게 좋을것 같아요

2023-11-10 09:33 UTC, PotentialY1 commented on src/channels/channels.controller.ts
> +@Controller('channels')
수정 완료

2023-11-10 09:38 UTC, PotentialY1 commented on src/channels/channels.service.ts
> +    const earliestOwnerRelation = await this.entityManager
커스텀 query 방식에서 EntityManager가 repository와 달리 raw SQL 쿼리 처리에 적합합니다.

2023-11-10 09:51 UTC, PotentialY1 commented on src/channels/channels.service.ts
> +
그게 request하는 UserRelation이 아니라 requestedUser가 되어야 합니다. 예외처리를 다 삭제하고 isAdmin만 남겼습니다.

2023-11-10 09:56 UTC, PotentialY1 commented on src/channels/channels.service.ts
> +
수정 완료

2023-11-10 09:57 UTC, PotentialY1 commented on src/channels/channels.service.ts
> +      .map((relation) => relation.user);
수정 완료

2023-11-10 10:00 UTC, PotentialY1 commented on src/channels/channels.service.ts
> +
삭제 완료

2023-11-10 10:06 UTC, izone00 commented on src/channels/channels.service.ts
> +
음 그 지금 if문이 inOwner == ture만 통과가 가능하거든
이 if문이 false일때 통과가 되어야할 거 같아요

onwer는 수정될수 없어서 이 예외처리는 필요합니다.

2023-11-10 10:09 UTC, izone00 commented on src/channels/channels.service.ts
> +    const earliestOwnerRelation = await this.entityManager
raw쿼리를 만들 이유가 있나요?
그냥 find에 지금만드신 조건문 넣으시고
아래도 save를 사용하면 똑같지 않을까요?

2023-11-10 10:13 UTC, PotentialY1 commented on src/channels/channels.service.ts
> +    const earliestOwnerRelation = await this.entityManager
raw쿼리를 써서 하는 방식을 공부해서 적용해봤는데 좀 더 간결한 형태로 변경했습니다.

2023-11-10 10:22 UTC, PotentialY1 commented on src/channels/channels.service.ts
> +
수정 완료

2023-11-10 10:28 UTC, PotentialY1 commented on src/channels/entities/channel.entity.ts
> +
네 owner에 대한 user인데 channel entity에 있는 user를 changeOwner 메소드와 createChannel 메소드에서 이미 쓰고 있습니다.

2023-11-10 10:30 UTC, PotentialY1 commented on src/users/user.entity.ts
> +
위와 동일

2023-11-10 13:22 UTC, izone00 reviewed
지금 channel Entity에 user를 정의해 소유자를 넣고 계신데
channelRelation에도 isOwner가 이미 정의되 있어서 필요가 없습니다.
changeOwner, createChannel안에 user를 모두 isOwner를 수정하거나 만드는걸로 바꿔주시고
이외에서 channel.user가 쓰인다면 다 고쳐야될것 갔습니다.

2023-11-10 13:22 UTC, izone00 commented on src/channels/channels.service.ts
> +
transferOwnership함수 내에서 더이상 사람이 없으면
throw new NotFoundException('소유자를 위임할 유저가 없습니다!'); 라는 에러를 던지고 있어서
지금 추가된 remainingUsers가 원하는 데로 작동하지 않습니다.

이거 두개를 합쳐주세요

2023-11-10 13:22 UTC, izone00 commented on src/channels/channels.service.ts
> +    }
return false가 어떤 역할을 하는건가요?

예외처리라면 이미 ban된 유저입니다. 라는 Error를 throw해주세요

2023-11-10 13:22 UTC, izone00 commented on src/channels/channels.service.ts
> +    }
Onwer는 kick될 수 없고
Admin또한 kick될 수 없게 되야 될 것 같습니다.

2023-11-10 13:22 UTC, izone00 commented on src/channels/channels.service.ts
> +    }
channel.password는 채널의 비밀번호인데 이게 있는지는 확인할 필요가 없는거 같아요
join할 유저가 입력한 비밀번호는 providedPassword입니다.

2023-11-10 13:22 UTC, izone00 commented on src/channels/channels.service.ts
> +    }
private이라도 친구초대 내역이있다면 join시켜줘야합니다.

2023-11-10 15:11 UTC, spew11 requested changes

2023-11-10 15:11 UTC, spew11 commented on src/channels/entities/channel.entity.ts
1. User 변수를 삭제하고, 이 변수와 관련된 메서드들도 함께 수정해 주세요.
2. channelRelations와 channelInvitations 변수에 cascade 설정을 추가하고 있지만, 이미 ChannelRelation 및 ChannelInvitation 엔티티에서 cascade를 설정하고 있으므로 이는 중복되기 때문에 cascade 설정을 제거하는 것이 바람직해 보입니다.

2023-11-10 15:11 UTC, spew11 commented on src/channels/channels.service.ts
> +      channelDto.password = await bcrypt.hash(password, salt);
channelDto.password에 클라이언트로부터 받은 채널 비밀번호를 암호화하여 저장하는 로직의 목적이 명확하지 않습니다. 이 부분은 제거하는 것이 좋아보여요.

2023-11-10 15:11 UTC, spew11 commented on src/channels/channels.service.ts
> +    const channel = this.channelRepository.create({ title, password, type, user: owner });
채널 생성 시, 클라이언트로부터 받은 비밀번호는 평문이 아닌 암호화된 형태로 저장해야 합니다.

2023-11-10 15:11 UTC, spew11 commented on src/channels/channels.service.ts
> +  async changeOwner(channelId: number, currentOwnerId: number, successorId: number): Promise<boolean> {
현재 changeOwner() 메서드에서는 channel에 있는 user 변수를 사용하는 로직이 구현되어 있습니다. 하지만 user 변수는 제거하기로 정했기때문에, 이에 따라 전체 로직을 수정해주시기 바랍니다. 또한, currentOwner의 hannel-relation 인스턴스에서 isOwner를 false로 설정하여 소유권을 제거하는 로직을 추가하는 것이 필요합니다.

2023-11-10 15:11 UTC, spew11 commented on src/channels/channels.service.ts
cancelBannedUser, kickUser, updateChannelRelation, changeOwner, join 메서드에서 경로 변수로 주어진 id에 해당하는 채널의 존재 여부를 확인하는 로직이 있습니다. 여기서 relations 옵션을 사용해 user 리스트까지 가져오는 것은 불필요해 보입니다. 삭제해주세요.

그리고 위처럼 직접 존재 여부를 확인하는 로직을 추가하는 대신에, 컨트롤러에서 channelById 파이프를 사용하여 채널 객체를 직접 받아오면, 코드가 더 간결해지고 채널의 존재 여부를 사전에 확인할 수 있고, 채널 객체를 직접 쿼리에 사용할 수 있어서 좋을 것 같아요!

2023-11-10 15:11 UTC, spew11 commented on src/channels/entities/channel-invitation.entity.ts
> +  @ManyToOne(() => User, (user) => user.channelInvitations)
유저 엔티티에만 cascade 설정을 하지 않으신 특별한 이유가 있나요? cascade 설정을 추가하는 것이 맞는 것 같아요.

2023-11-10 15:11 UTC, spew11 commented on src/channels/entities/channel-relation.entity.ts
> +  @ManyToOne(() => User, (user) => user.channelRelations)
유저 엔티티에만 cascade 설정을 하지 않으신 특별한 이유가 있나요? cascade 설정을 추가하는 것이 맞는 것 같아요.

2023-11-14 13:33 UTC, spew11 approved these changes

2023-11-14 13:41 UTC, izone00 approved these changes

2023-11-14 13:41 UTC, merged